language: csharp
dotnet: 3.0.101
mono: none

script:
  - dotnet build TSIM.sln
  - dotnet test TSIM.Tests/TSIM.Tests.csproj
  - time dotnet run --project TSIM/TSIM.csproj -- simdb.sqlite --importscenario data/scenario.json --simulate --rendersvg output.svg
